### ISSUE TITLE
Twilio용 람다 함수 배포

### ISSUE THREAD

**Issue by mdgarden** [mdgarden/bleDrill#6]
## 내용
- 현재 RN에서 SMS를 전송할 수 있는 방법은 Twilio를 통한 API통신 밖에 없음
- RN상에서 Twilio 클라이언트를 이용할 수 없음
- Twilio용 람다 함수를 작성하여 배포 (severless.js 이용)

## Task
- [x] 서버레스 프레임워크 셋업
- [x] twilio 테스트 함수 작성
- [x] 배포
- [x] 배포 후 테스트 함수 작동 확인
- [x] ~~위치, 날짜 정보를 포함한 템플릿으로 수정~~ > 앱에서 완성된 메세지로 보내는 것으로 변경

**Comment by mdgarden** [comment]
엔드포인트
https ://iabcqf2t99.execute-api.us-east-1.amazonaws.com/dev/api/sendText
